[package]
name = "mandate-registry"
version = "0.3.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { version = "=26.1.0", features = ["experimental_spec_shaking_v2"] }
stellar-access = "=0.7.2"
stellar-contract-utils = "=0.7.2"

[dev-dependencies]
reapp-timelock-controller = { path = "../timelock-controller" }
soroban-sdk = { version = "=26.1.0", features = ["testutils"] }
stellar-governance = "=0.7.2"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
lto = true
panic = "abort"
codegen-units = 1
