import { githubBuild } from "./github-build.mjs";
import { parseArgs } from "node:util";
import { writeFile } from "node:fs/promises";
import { connect, read, scValToNative, wasm } from "./rpc.mjs";
import { codeHash, manifest, V2, V2_ADMIN } from "./transfer.mjs";
import { V2_WASM_HASH } from "./release.mjs";
const { values: v } = parseArgs({ options: Object.fromEntries(["network", "source", "helper", "governance", "out", "build-run", "build-commit"].map((key) => [key, { type: "string" }])) });
if (!v.out || !v.governance) throw new Error("--out and explicit --governance required");
const ctx = await connect(v.network);
const config = scValToNative(await read(ctx, v.source, v.helper, "get_config"));
const artifact = v.network === "mainnet" || v["build-run"] ? await githubBuild(v["build-run"], v["build-commit"]) : null;
const helper = artifact ? { hash: Buffer.from(artifact.build.hashes.timelock, "hex") } : await wasm("timelock");
const hashesCtx = { ...ctx, m: { network: v.network } };
const deployedHash = await codeHash(hashesCtx, v.helper);
if (deployedHash !== helper.hash.toString("hex")) throw new Error("Helper code differs from local reviewed build");
const targetWasmHash = await codeHash(hashesCtx, config.target);
if (v.network === "mainnet" && (config.target !== V2 || (config.initial_admin.startsWith("G") && config.initial_admin !== V2_ADMIN) || targetWasmHash !== V2_WASM_HASH)) throw new Error("Production target differs from reviewed V2 deployment");
const previousHelperWasmHash = config.initial_admin.startsWith("C") ? await codeHash(hashesCtx, config.initial_admin) : undefined;
const file = manifest({ version: 1, network: v.network, target: config.target, helper: v.helper, initialAdmin: config.initial_admin, governance: v.governance, delayLedgers: config.delay, helperWasmHash: deployedHash, targetWasmHash, maxFeeStroops: "500000000", ...(previousHelperWasmHash ? { previousHelperWasmHash } : {}) }, v.governance);
await writeFile(v.out, `${JSON.stringify(file, null, 2)}\n`, { mode: 0o600, flag: "wx" });
console.log(`Deployment file: ${v.out}`);
